
services:
  grafana:
    image: "grafana/grafana:7.3.7"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/data-sources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    depends_on:
      - prometheus

  prometheus:
    image: "prom/prometheus:v2.24.1"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/etc/prometheus/data"
    depends_on:
      - node_app

  node_app:
    build:
      context: ./
    ports:
      - "8080:8080"